# Generated by Django 3.2.4 on 2021-07-05 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificacion del pais')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('numeroIdentificacion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificacion del proveedor')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del proveedor')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono del proveedor')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion del proveedor')),
                ('email', models.CharField(max_length=50, verbose_name='Email del proveedor')),
                ('clave', models.CharField(max_length=8, verbose_name='Clave del proveedor')),
                ('moneda', models.CharField(max_length=10, verbose_name='Clave del proveedor')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groundZero.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('idInsumo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificacion del insumo')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del insumo')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion del insumo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groundZero.proveedor')),
            ],
        ),
    ]
